version: 2
updates:
- package-ecosystem: gomod
  directory: "/"
  schedule:
    interval: daily
    time: "12:00"
  open-pull-requests-limit: 10
  ignore:
  - dependency-name: github.com/onsi/gomega
    versions:
    - 1.10.5
  - dependency-name: github.com/onsi/ginkgo
    versions:
    - 1.15.0
  - dependency-name: github.com/bwmarrin/discordgo
    versions:
    - 0.23.1
