version: 2
jobs:
  build:
    working_directory: ~/aegiseek
    docker:
      - image: node:13-buster-slim
    steps:
      - checkout
      - restore_cache:
          key: dependency-cache-{{ checksum "package.json" }}
      - run:
          name: Install project dependencies
          command: yarn install
      - save_cache:
          key: dependency-cache-{{ checksum "package.json" }}
          paths:
            - ./node_modules
      - run:
          name: Run unit tests
          command: yarn test --coverage
      - run:
          name: Lint
          command: yarn lint
      - store_artifacts:
          path: junit
      - store_artifacts:
          path: coverage
      - store_test_results:
          path: junit
