version: 2
jobs:
  build:
    working_directory: ~/aegiseek
    docker:
      - image: node:13-buster-slim
    steps:
      - checkout
      - run:
          # https://circleci.com/docs/2.0/custom-images/#adding-required-and-custom-tools-or-files
          name: Install CircleCI dependencies
          command: apk add --no-cache ca-certificates
      - run:
          name: Install Yarn
          command: npm install -g yarn
      - restore_cache:
          key: dependency-cache-{{ checksum "package.json" }}
      - run:
          name: Install project dependencies
          command: yarn install
      - save_cache:
          key: dependency-cache-{{ checksum "package.json" }}
          paths:
            - ./node_modules
      - run:
          name: Run unit tests
          command: yarn test-once --coverage
      - run:
          name: Lint
          command: yarn lint
      - store_artifacts:
          path: junit
      - store_artifacts:
          path: coverage
      - store_test_results:
          path: junit
